permissions:                    # Global permissions configuration starts here
  contents: write                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests

name: update-readme

off:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run the script
        run: python .github/update_readme.py
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add README.md
          if git diff-index --quiet HEAD --; then
            echo "changes_to_push=false" >> $GITHUB_ENV
          else
            git commit -m "Updated README"
            echo "changes_to_push=true" >> $GITHUB_ENV
          fi
      - name: Push changes # push the output folder to your repo
        if: ${{ env.changes_to_push == 'true' }}
        uses: ad-m/github-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          force: true